---
title: "Publications"
---

# Publications

Below is a list of publications for **Kate Schneider Lecy** 
as indexed on Google Scholar.

## Peer-reviewed articles

- KR Schneider, R Remans, TH Bekele, D Aytekin, P Conforti, S Dasgupta, ... (2025). *Governance and resilience as entry points for transforming food systems in the countdown to 2030*. _Nature Food_. Cited 17 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:dhFuZR0502QC).
- OT Westengen, KS Lecy, A Angelsen, ME Aspholm, N Bjugstad, ... (2025). *Three reasons why food system transformations are contested, and why food system scientists and policymakers should care*. _Frontiers in Sustainable Food Systems_. Cited 1 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:_Qo2XoVZTnwC).
- R Manners, J Warner, K Schneider, E Matsiko, H Vasanthakaalam, ... (2025). *Deploying high-frequency market data to estimate the cost of recommended diets: Recent trends in Rwanda*. _Intl Food Policy Res Inst_. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:bEWYMUwI8FkC).
- A Thorne-Lyman, K Schneider, D Altema-Johnson, KC Angela, H Lee, ... (2025). *Strategies to Boost Consumption of Beans, Peas, and Lentils: Results of a National Survey of Americans*. _Current Developments in Nutrition_. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:e5wmG9Sq2KIC).
- KR Schneider, AP De la O Campos, R Cavatassi, B Davis (2024). *Resilient and inclusive rural transformation in sub-Saharan Africa under climate, demographic, and social change: Challenges and opportunities for income growth and job creation*. _Global Food Security_. Cited 11 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:d1gkVwhDpl0C).
- D Dewi, D Aytekin, KR Schneider, N Covic, J Fanzo, S Nordhagen, ... (2024). *Defining and measuring policy coherence for food system transformation: A scoping review*. _Global Food Security_. Cited 9 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:mB3voiENLucC).
- KR Schneider (2024). *Health–environment interactions across food systems*. _Nature Food_. Cited 1 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:eQOLeE2rZwMC).
- K Schneider, CB Barrett (2024). *Estimating Output Value Added of Global Agrifood Systems*. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:hC7cP41nSMkC).
- K Schneider, S Hendriks, D Resnick (2024). *Health-Related Food Environment Policies*. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:IjCSPb-OGe4C).
- K Schneider (2024). *Keynote: Understanding Interactions Across Food System Indicators and their Implications to Bring About Transformative Change*. _Food Systems Research Center, University of Vermont_. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:R3hNpaxXUhUC).
- KR Schneider, J Fanzo, L Haddad, M Herrero, JR Moncayo, A Herforth, ... (2023). *The state of food systems worldwide in the countdown to 2030*. _Nature Food_. Cited 151 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:hFOr9nPyWt4C).
- KR Schneider, L Christiaensen, P Webb, WA Masters (2023). *Assessing the affordability of nutrient‐adequate diets*. _American Journal of Agricultural Economics_. Cited 15 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:aqlVkmm33-oC).
- KR Schneider, A Bellows, S Downs, W Bell, R Ambikapathi, S Nordhagen, ... (2023). *Inequity in access to healthy foods*. _Food System Economics Commission_. Cited 6 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:Se3iqnhoufwC).
- KR Schneider, J Fanzo, L Haddad, M Herrero, JR Moncayo, A Herforth, ... (2023). *The food systems countdown report 2023: the state of food systems worldwide*. _Columbia University; Cornell University; Food and Agriculture Organization …_. Cited 2 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:Zph67rFs4hoC).
- IR Cliffer, A Marshak, KR Schneider, A Venkat, EN Naumova (2023). *Seasonality of nutrition*. _Academic Press_. Cited 1 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:qUcmZB5y_30C).
- R Ambikapathi, KR Schneider, B Davis, M Herrero, P Winters, JC Fanzo (2022). *Global food systems transitions have enabled affordable diets but had less favourable outcomes for nutrition, environmental health, inclusion and equity*. _Nature Food_. Cited 218 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:YsMSGLbcyi4C).
- KR Schneider (2022). *Nationally representative estimates of the cost of adequate diets, nutrient level drivers, and policy options for households in rural Malawi*. _Food Policy_. Cited 21 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:M3ejUd6NZC8C).
- J Fanzo, L Haddad, KR Schneider, C Bene, NM Covic, A Guarin, ... (2022). *Rigorous monitoring is necessary to guide food system transformation in the countdown to the 2030 global goals (vol 104, 100784, 2021)*. _Food Policy_. Cited 1 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:qxL8FJ1GzNcC).
- K Schneider (2022). *meet the food system transformation challenge in the countdown to 2030 global goals. Food*. _Maternal & Child Nutrition_. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:W7OEmFMy1HYC).
- J Fanzo, L Haddad, KR Schneider, C Béné, NM Covic, A Guarin, ... (2021). *Rigorous monitoring is necessary to guide food system transformation in the countdown to the 2030 global goals*. _Food Policy_. Cited 364 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:qjMakFHDy7sC).
- KR Schneider, P Webb, L Christiaensen, WA Masters (2021). *Assessing diet quality where families share their meals: evidence from Malawi*. _The Journal of nutrition_. Cited 10 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:_kc_bZDykSQC).
- KR Schneider, J Oslund, T Liu (2021). *Impact of the community eligibility provision program on school meal participation in Texas*. _Public Health Nutrition_. Cited 10 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:5nxA0vEk-isC).
- KR Schneider (2021). *Household consumption, individual requirements, and the affordability of nutrient-adequate diets–An application to Malawi*. _Tufts University, Gerald J. and Dorothy R. Friedman School of Nutrition …_. Cited 9 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:2osOgNQ5qMEC).
- S Kaiyatsa, KR Schneider, WA Masters (2021). *How sensitive are cost of living metrics to missing food price data? Evidence from a novel market survey and consumer price data in rural Malawi.*. Cited 2 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:_FxGoFyzp5QC).
- KR Schneider, JC Fanzo, L Haddad, JR Moncayo (2021). *Global health has a stake in the upcoming UN Food Systems Summit*. _The Lancet_. Cited 1 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:ULOm3_A8WrAC).
- K Schneider, L Christiaensen, PJ Webb, WA Masters (2021). *Affordability of Nutrient-Adequate Diets at the Household Level*. _< bound method Organization. get_name_with_acronym of< Organization: World …_. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:RHpTSmoSYBkC).
- K Schneider, L Christiaensen, P Webb, WA Masters (2021). *Policy Research Working Paper 9834*. _Policy_. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:3fE2CSJIrl8C).
- WA Masters, K Schneider, L Christiaensen, P Webb (2021). *Availability, Seasonality, and Affordability of Nutritious Diets for All–Evidence from Malawi*. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:TQgYirikUcIC).
- K Schneider, L Christiaensen, P Webb, WA Masters (2021). *Availability, Seasonality, and Affordability of Nutritious Diets for All–Evidence from Malawi*. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:kNdYIx-mwKoC).
- K Schneider, A Herforth (2020). *Software tools for practical application of human nutrient requirements in food-based social science research*. _Gates Open Research_. Cited 29 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:-f6ydRqryjwC).
- K Schneider, L Christiaensen, P Webb, W Masters (2020). *The cost of nutritious diets for individuals and households in rural Malawi*. _Current Developments in Nutrition_. Cited 2 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:4TOpqqG69KYC).
- K Schneider, W Masters, P Webb, L Christiaensen (2020). *Sources, intake levels, and shadow prices of essential nutrients in rural Malawi: evidence from household surveys and market prices reveal the cost of vitamins and minerals*. Cited 1 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:L8Ckcad2t8MC).
- K Schneider, WA Masters, P Webb, L Christiaensen (2020). *Food Policy Metrics for Access to Affordable Healthy Diets*. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:MXK_kJrjxJIC).
- JL Oslund, T Liu, K Schneider (2020). *Impact of the Community Eligibility Program on School Meal Participation in Texas*. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:WF5omc3nYNoC).
- G Seymour, YJ Masuda, J Williams, K Schneider (2019). *Household and child nutrition outcomes among the time and income poor in rural Bangladesh*. _Global food security_. Cited 48 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:u-x6o8ySG0sC).
- K Schneider, MK Gugerty (2019). *The impact of export-driven cash crops on smallholder households*. _Gates Open Res_. Cited 29 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:zYLM7Y9cAGgC).
- K Schneider, WA Masters (2019). *Orange Fanta versus orange fruit: A novel measure of nutrition knowledge in Malawi*. _Maternal & child nutrition_. Cited 10 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:mVmsd5A6BfQC).
- S Kaiyatsa, WA Masters, Y Bai, K Schneider, A Herforth (2019). *Do remote rural people pay higher prices for more nutritious foods? Evidence from 130,975 price observations at rural markets in Malawi, 2007-2017*. Cited 7 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:ufrVoPGSRksC).
- K Schneider, W Masters (2019). *Nutrient Adequacy at the Household Level and the Cost of Nutritious Diets in Malawi (P10-055-19)*. _Current Developments in Nutrition_. Cited 2 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:UeHWp8X0CEIC).
- K Schneider, WA Masters (2019). *Advancing the use of household surveys for nutrition: Nutrient adequacy at the household level and the cost of nutritious diets in Malawi*. Cited 1 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:7PzlFSSx8tAC).
- K Schneider (2019). *Quarterly Commodity Price Update: Fourth Quarter 2010*. _Gates Open Res_. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:IWHjjKOFINEC).
- A Tuenter, PKB Nino, A Vitezova, A Pantavos, WM Bramer, OH Franco, ... (2019). *Maternal and Child Nutrition Volume 15*. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:4JMBOYKVnBMC).
- K Schneider, WA Masters (2018). *Orange Fanta vs orange fruit: A novel measure of nutrition knowledge and women’s diet quality in Malawi*. Cited 0 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:8k81kl-MbHgC).
- P Pingali, K Schneider, M Zurek (2014). *Poverty, agriculture and the environment: The case of Sub-Saharan Africa*. _Springer_. Cited 67 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:4DMP91E08xMC).
- K Schneider, MK Gugerty (2011). *Agricultural productivity and poverty reduction: Linkages and pathways*. _Evans School Review_. Cited 231 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:KlAtU1dfN6UC).
- K Schneider, L Anderson (2010). *Yield gap and productivity potential in Ethiopian agriculture: Staple grains & pulses*. _EPAR brief_. Cited 89 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:LkGwnXOMwfcC).
- K Schneider, MK Gugerty (2010). *Gender and contract farming in sub-Saharan Africa–Literature review*. _Seattle USA: Evans School of Public Affairs, University of Washington_. Cited 32 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:u5HHmVD_uO8C).
- K Schneider, R Plotnick (2010). *Poultry market in West Africa: overview and comparative analysis*. _EPAR Brief_. Cited 17 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:Wp0gIr-vW9MC).
- J Armah, K Schneider, R Plotnick, MK Gugerty (2010). *Smallholder contract farming in sub-Saharan Africa and South Asia*. _Evans School Policy Analysis and Research_. Cited 9 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:j3f4tGmQtD8C).
- K Schneider, R Plotnick (2010). *Poultry market in West Africa: Burkina Faso*. _Evans School of Public Affairs University. EPAR Brief_. Cited 7 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:r0BpntZqJG4C).
- K Schneider, M Kay (2010). *Gender & contract farming in Sub-Saharan Africa*. _Literature Review. Evans School of Public Affairs, University of Washington_. Cited 6 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:iH-uZ7U-co4C).
- MK Gugerty, K Schneider (2010). *The impact of export-driven cash crops on smallholder households*. Cited 1 times on [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=lWGTfD4AAAAJ&hl&citation_for_view=lWGTfD4AAAAJ&hl:hqOjcs7Dif8C).
